### PR TITLE
Add UserIFC

### PR DESCRIPTION
**Pull request by davemachado**
Add UserIFC JAVA file for implementation.

### CODE REVIEW

**Comment by davemachado** [comment]
@OnlyLAGcanSTOPme , during our meeting today, we decided to remove the setters from this global interface file because only the profiler should be setting any attribute - the other features only need to "get" attributes.

**Comment by davemachado** [comment]
I need at least 2 (+1)'s from contributors to merge pull request. There might still be some additional getters needed for different features, but those can be added after the fact.

**Comment by DanielDiTommaso** [comment]
+1
Are files auto converted w/ crlf between dos/unix?

**Comment by davemachado** [comment]
If the files are saved with no Unicode special characters, I don't see why plain text would be a problem whether it's dos or UNIX.

**Comment by OnlyLAGcanSTOPme** [comment]
+1

**Comment by OnlyLAGcanSTOPme** [comment]
Hi Dave,

Are we supposed to add new file from the GitHub ? Is it how you usually add
files? Or do you do that from Eclipse?

Thanks
Sungsoo

**Comment by OnlyLAGcanSTOPme** [comment]
What is your email address anyway?

**Comment by davemachado** [comment]
Hey Sungsoo,

I've sent an email out to everyone so all email addresses are shared. 

When you edit within a repo on your account, any additions, deletions, or edits to any files will be fracked. Therefore, you can make as many new files locally as you want and git should track them. Let me know if that clears things up.

**Comment by OnlyLAGcanSTOPme** [comment]
ok so I was able to pull the files from GitHub successfully to set up the
(general) project in Eclipse but when I try to create a java file it says
this is not java project so you can't create one. Have you had this kind
issue?

Thanks

**Comment by davemachado** [comment]
Continued in Issue #27

**Pull request merged**
