### PR TITLE
Create UserProfile.java

### PR DESCRIPTION
**Pull request by OnlyLAGcanSTOPme**
Create UserProfile.java 

Will add a delete function

### CODE REVIEW

**Comment by davemachado** [comment]
What is the purpose of this file/function? Is it just taking passed in data and assigning it to various objects in the User class? If that's the case, it's missing the actual user inputs and saving this person in a file. Can you elaborate on your plan for this whole module in terms of implementation? Thanks in advance!

**Comment by OnlyLAGcanSTOPme** [comment]
Moved all the User's getters and setters to a separate "User" class. Now UserProfile's purpose is to contain a list of Profiles, load profiles from files, and add, update to files. Currently adding User Profile Info to a file is functional. 

My next goal is to make it so that user is able to set "Current" profile and load the profile into the application. How to use this class? 
Place this when user requests for UserProfile:
		UserProfile UserProf = new UserProfile();
		UserProf.Start();

**Comment by davemachado** [comment]
Looks like a great start Sungsoo! +1

**Comment by OnlyLAGcanSTOPme** [comment]
Thanks Dave.

**Comment by OnlyLAGcanSTOPme** [comment]
Hi guys,
I updated my file. Now it can load all saved profiles from a file.
Now you can access the user's current profile's ID number by calling
UserProfile UserProf = new UserProfile();
UserProf.Start();
int hi = UserProf.getCurrentProfileID();

Let me know what you guys think and if you need anything other user info than ID.

Sungsoo

**Comment by davemachado** [comment]
Hi Sungsoo,

You need to add the file to be staged in a branch. That branch will then take all pushed updates, even if a PR for that branch is already in progress. Make sense?

**Comment by ron12013** [comment]
+1

**Comment by davemachado** [comment]
@OnlyLAGcanSTOPme Sungsoo, this is ready to be merged. :)

**Comment by OnlyLAGcanSTOPme** [comment]
Hi Dave, I think I get it. But few questions. So when I want add a 'new' file, create a new branch just like image 1 right? 
 And then add a new source file and then committ/pull request when ready?
And then this will be merged to your develop.
I think I did the same steps for my previous merge.

**Pull request merged**
