### PR TITLE
Feature/Add Menu and Input Handling

### PR DESCRIPTION
**Pull request by davemachado**
Note: Using gitFlow standard for namng branches/pull requests [feature/, hotfix/, release/).

This PR includes the initial implementation of the main menu and input handling for said menu. Upon user entering choice, the menu will just output a text-based version of future function/feature main methods.

### CODE REVIEW

**Comment by davemachado** [comment]
Could this get reviewed by two developers please? Thank you!

**Comment by ron12013** [comment]
+1

**Comment by davemachado** [comment]
@ron12013 good question. The idea I had was to call the user profiler to do whatever updates/detail entry is needed (using its own switch statement to select certain details) and passing back that whole object. @OnlyLAGcanSTOPme, does that make sense Sungsoo? Feel free to clarify if needed! :)

**Comment by davemachado** [comment]
Also, @OnlyLAGcanSTOPme, if you could look at this and give it a thumbs-up if it look good, I would appreciate it.

**Comment by OnlyLAGcanSTOPme** [comment]
Hi guys, so once you create the  user profile object, you will see the menu items. If you select 2) Add Profile", you will be prompted to enter details. For now, there are only 2,3 items to enter since we have created our own types. Can someone create new classes for the types that are expressed in our interface?

**Comment by OnlyLAGcanSTOPme** [comment]
+1

**Comment by OnlyLAGcanSTOPme** [comment]
And how is everyone?

**Comment by davemachado** [comment]
Doing well Sungsoo, thanks. I appreciate the info on how the profiler will be called...good to know for the menu. Cheers!

**Pull request merged**
