### PR TITLE
401k calculator

### PR DESCRIPTION
**Pull request by DanielDiTommaso**
Quick demo of 401k Calc. Mocked person object using local variables. Next to no advanced functionality, and interest calculation is off. Will update for next sprint. More practice branching,committing,pushing,pull request than anything else!

### CODE REVIEW

**Comment by davemachado** [comment]
@DanielDiTommaso , I've added the supporting info to this PR (sprint, pipeline, etc). Currently this PR is looking to merge the changes into 'master', but we need to merge into 'develop'. Therefore, we are going to need to close this PR and open a new one - just make sure to set the merge into 'develop'. Thanks Dan!

**Comment by DanielDiTommaso** [comment]
@davemachado Ahhh, that explains why changes you made last week were in my PR. This is why we practice. Good catch!

**Comment by davemachado** [comment]
tip: that's why this PR is showing the files I pushed (main.java, readme) as changes - because 'master' does not have those changes yet as they are in #24

**Comment by DanielDiTommaso** [comment]
Its late okay :P                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Dave MachadoSent: Wednesday, July 6, 2016 11:44 PMTo: davemachado/Finance-PlannerReply To: davemachado/Finance-PlannerCc: DanielDiTommaso; MentionSubject: Re: [davemachado/Finance-Planner] 401k calculator (#28)tip: that's why this PR is showing the files I pushed (main.java, readme) as changes - because 'master' does not have those changes yet as they are in #24 

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request closed without merging**
